CREATE TABLE users (
    tg_id BIGINT UNIQUE NOT NULL,
    first_name varchar(128),
    last_name varchar(128),
    tg_access jsonb
);

CREATE TABLE lines (
    point_control BIGINT PRIMARY KEY NOT NULL,
    line_name varchar(255) NOT NULL
);

CREATE TABLE history_regimes (
    id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    line_id BIGINT references lines(point_control),
    product_name varchar(255),
    regime int NOT NULL,
    bottles_count BIGINT,
    alko_volume numeric(11, 3),
    over_alko_volume numeric(21, 5) NOT NULL,
    over_bottles_counts BIGINT NOT NULL,
    beg_time timestamp NOT NULL,
    end_time timestamp,
    UNIQUE (line_id, beg_time)
);

CREATE TABLE intervening_data_lines (
    line_id BIGINT references lines(point_control),
    over_alko_volume numeric(21, 5) NOT NULL,
    over_bottles_counts BIGINT NOT NULL,
    create_time timestamp NOT NULL DEFAULT now()
);

CREATE INDEX idx_beg_time ON history_regimes (beg_time);
CREATE INDEX idx_line_id_reg ON history_regimes (line_id);
CREATE INDEX idx_regime ON history_regimes (regime);

CREATE INDEX idx_time ON intervening_data_lines (create_time);
CREATE INDEX idx_line_id_interv ON intervening_data_lines (line_id);


INSERT INTO lines (point_control, line_name) VALUES (2, 'Линия розлива №2');
INSERT INTO lines (point_control, line_name) VALUES (3, 'Спиртоприемное отделение');
INSERT INTO lines (point_control, line_name) VALUES (4, 'Линия розлива №1');
INSERT INTO lines (point_control, line_name) VALUES (5, 'Линия розлива №3');
INSERT INTO lines (point_control, line_name) VALUES (6, 'Производство дистиллятов');

/*
tg_access = '{"warning_bottling": 1, "end_bottling": 1, "night_warning": 1, "value_warning": 1,
              "set_volume_to_stop": 1}'
*/


INSERT INTO users (tg_id, first_name, last_name, tg_access) 
            VALUES (476048675, 'Владимир', 'Чуркин', '{"warning_bottling": 1, "end_bottling": 1, "night_warning": 1, "value_warning": 1,
              "set_volume_to_stop": 1}');

INSERT INTO users (tg_id, first_name, last_name, tg_access) 
            VALUES (409952582, 'Сергей', 'Чуркин', '{"warning_bottling": 1, "end_bottling": 1, "night_warning": 1, "value_warning": 1,
              "set_volume_to_stop": 1}');

INSERT INTO users (tg_id, first_name, last_name, tg_access) 
            VALUES (1128438137, 'Диана', 'Дебольская', '{"warning_bottling": 0, "end_bottling": 1, "night_warning": 0, "value_warning": 1,
              "set_volume_to_stop": 0}');


CREATE USER bottling_reporter_bot WITH PASSWORD 'Def123321!';
GRANT ALL PRIVILEGES ON SCHEMA public to bottling_reporter_bot;

